print("----------------------------------------")
print("Tugas 1 SISOP Kelas-A")
print("----------------------------------------")
print("Nama: Fiqih Pavita Andharluana")
print("NPM: 21083010042")
print("----------------------------------------")
print("Notes:")
print("----------------------------------------")
print("Hallo dunia!")
print("Ini adalah skrip Bash pertamaku di Linux")
